var dist = require('./dist');
var api = require('./api');
var rest = require('./rest');
var profile = require('./profile');
var storage = require('./storage');
var stream = require('./stream');
var exam = require('./exam');
var student = require('./student');
var inspector = require('./inspector');
var notes = require('./notes');
var chat = require('./chat');
var members = require('./members');
var tools = require('./tools');
module.exports = function(app) {
    app.use('/dist', dist);
    app.use('/api', api);
    app.use('/rest', rest);
    app.use('/profile', profile);
    app.use('/storage', profile.isAuth, storage);
    app.use('/tools', profile.isAuth, tools);
    app.use('/exam', profile.isStudent, exam);
    app.use('/student', profile.isStudent, student);
    app.use('/chat', profile.isStudent, chat);
    app.use('/members', profile.isStudent, members);
    app.use('/notes', profile.isInspector, notes);
    app.use('/inspector', profile.isInspector, inspector);
    app.use('/stream', profile.isInspector, stream);
};