var dist = require('./dist');
var api = require('./api');
var rest = require('./rest');
var profile = require('./profile');
var storage = require('./storage');
var stream = require('./stream');
var exam = require('./exam');
var student = require('./student');
var inspector = require('./inspector');
var verify = require('./verify');
var notes = require('./notes');
var chat = require('./chat');
var members = require('./members');
var tools = require('./tools');
var admin = require('./admin');
var user = require('./user');
var schedule = require('./schedule');
module.exports = function(app) {
    app.use('/dist', dist);
    app.use('/api', api);
    app.use('/rest', rest);
    app.use('/profile', profile);
    app.use('/storage', profile.isAuth, storage);
    app.use('/tools', profile.isAuth, tools);
    app.use('/student', profile.isStudent, student);
    app.use('/chat', profile.isStudent, chat);
    app.use('/members', profile.isStudent, members);
    app.use('/notes', profile.isInspector, notes);
    app.use('/inspector', profile.isInspector, inspector);
    app.use('/verify', profile.isInspector, verify);
    app.use('/stream', profile.isAdministrator, stream);
    app.use('/admin', profile.isAdministrator, admin);
    app.use('/exam', profile.isAdministrator, exam);
    app.use('/user', profile.isAdministrator, user);
    app.use('/schedule', profile.isAdministrator, schedule);
};